baseurl = "https://r4all.github.io/website"
languageCode = "en-us"
title = "The R4All Website"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  editURL = "https://github.com/R4All/website/master/content/"
  description = "The R4All Website"
  author = "ODAN"
  autoNav = true
  search = true
